---
###
## Create Security Groups and EC2 Instances
#

# Wwe create our Main Security Group.
# Basically the idea here is to allow SSH access
# from your IP to the EC2 resources you will
# start in your VPC.

- name: Gather EC2 VPC facts
  ec2_vpc_net_facts:
    region: "{{ provider_region }}"
  register: vpcs
  tags:
    - create

- name: Getting the facts from the defaults via the Network template for ingress rules
  set_fact:
    from_template: "{{ lookup('template', './network.j2') }}"
  vars:
    to_template_aws_security_groups: "{{ aws_security_groups }}"
    to_template_vpcs: "{{ vpcs }}"
  tags:
    - create

- name: Provision EC2 security groups for inbound rules
  ec2_group:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    region: "{{ item.region }}"
    state: present
    rules: "{{ item.rules }}"
  with_items: "{{ from_template.aws_security_groups }}"
  tags:
    - create

- name: Debug the variables
  debug: var=hostvars[inventory_hostname]
  tags:
    - create

#- name: Create the egress rules against the existing security groups (note not best way as other via template)
#  ec2_group:
#    name: "{{ item.name }}"
#    description: "{{ item.description }}"
#    region: "{{ item.region }}"
#    state: present
#    rules_egress:
#      - proto: "{{ item.proto }}"
#        from_port: "{{ item.from_port }}"
#        to_port: "{{ item.to_port }}"
#        cidr_ip: "{{ item.cidr_ip }}"
#    with_items:
#      - "{{ aws_security_groups_egress_7_0 }}"
#      - "{{ aws_security_groups_egress_7_1 }}"
#      - "{{ aws_security_groups_egress_7_2 }}"
#      - "{{ aws_security_groups_egress_7_3 }}"
#      - "(( aws_security_groups_egress_7_4 }}"
#    tags:
#      - create

- name: Getting the facts from the defaults via the Network template for egress rules
  set_fact:
    from_template_egress: "{{ lookup('template', './network_egress.j2') }}"
  vars:
    to_template_aws_security_groups_egress: "{{ aws_security_groups_egress }}"
    to_template_vpcs: "{{ vpcs }}"
  tags:
    - create

- name: Debug the variables
  debug: var=hostvars[inventory_hostname]
  tags:
    - create

#- name: Provision EC2 security groups for outbound rules
#  ec2_group:
#    name: "{{ item.name }}"
#    description: "{{ item.description }}"
#    region: "{{ item.region }}"
#    state: present
#    rules_egress: "{{ item.rules }}"
#  with_items: "{{ from_template.aws_security_groups_egress }}"
#  tags:
#    - create

# Create our Servers from the templates

#- name: Getting the facts from the defaults via the compute template
#  set_fact:
#    from_template: "{{ lookup('template', './compute.j2') }}"
#  vars:
#    to_template_instance_server_create: "{{ instance_server_create }}"
#  tags:
#    - create

- name: Provision EC2 Instance
  ec2:
    region: "{{ provider_region }}"
    group: "{{ item.security_group }}"
    key_name: "{{ item.key_name }}"
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.image }}"
    state: present
    wait: yes
    wait_timeout: 300
    count: "{{ item.count }}"
#    exact_count: "{{ item.exact_count }}"
    count_tag: "{{ item.count_tags }}"
    instance_tags: "{{ item.instance_tags }}"
  with_items:
    - "{{ rhel_7_0 }}"
    - "{{ rhel_7_1 }}"
    - "{{ rhel_7_2 }}"
    - "{{ rhel_7_3 }}"
    - "{{ rhel_7_4 }}"
  tags:
    - ec2
